# Generated by Django 3.2.9 on 2021-11-26 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music_styles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('repeat_event', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('N', 'None')], default='N', max_length=1)),
                ('details', models.TextField()),
                ('base_price', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adresses.adressesmodel')),
                ('candidatures', models.ManyToManyField(related_name='candidatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_datetime', models.DateTimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventmodel')),
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='lineup',
            field=models.ManyToManyField(related_name='events', through='events.LineupEvent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='music_styles',
            field=models.ManyToManyField(to='music_styles.MusicStyleModel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
