# Generated by Django 3.2.9 on 2021-11-29 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('music_styles', '0001_initial'),
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupeventmodel',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineupeventmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventmodel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adresses.adressesmodel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='candidatures',
            field=models.ManyToManyField(related_name='candidatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='lineup',
            field=models.ManyToManyField(related_name='events', through='events.LineupEventModel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='music_styles',
            field=models.ManyToManyField(to='music_styles.MusicStyleModel'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
