# Generated by Django 3.2.9 on 2021-11-30 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineupeventmodel',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lineupeventmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_set', to='events.eventmodel'),
        ),
    ]
