# Generated by Django 3.2.9 on 2021-12-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211130_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='repeat_event',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('None', 'None')], default='None', max_length=7),
        ),
    ]
