# Generated by Django 3.2.9 on 2021-12-02 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventmodel_repeat_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbacks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventmodel'),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
